default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: rvf_development

test:
  <<: *default
  database: rvf_test

production:
  <<: *default
  database: rvf_production
  username: <%= ENV['RVF_DATABASE_USERNAME'] %>
  password: <%= ENV['RVF_DATABASE_PASSWORD'] %>
