name: Deploy backend to Heroku

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # フル履歴取得
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # サブツリーを切り出して一時ブランチ heroku-deploy を作成
      - name: Split backend subtree
        run: git subtree split --prefix backend -b heroku-deploy

      # Heroku リモートを追加＆強制プッシュ
      - name: Push to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git
          git push heroku heroku-deploy:main --force

      # 後片付け（オプション）
      - name: Delete temp branch
        run: git branch -D heroku-deploy || true
